name = "napari_svg"
display_name = "Napari SVG"
license = "BSD-3-Clause"
entry_point = "napari_svg"

[[contributions.commands]]
id = "napari_svg.svg_writer"
title = "Napari SVG writer"
python_name="napari_svg.hook_implementations:writer"

[[contributions.writers]]
command = "napari_svg.svg_writer"
layer_types = ["image","labels","points","shapes","vector"]
filename_extensions = [".svg"]